name: C/C++ CI

on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: make
      run: make
